services:
  db:
    container_name: Controle_de_Fluxo_DB
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB}
      POSTGRES_USER: ${USER_DB}
      POSTGRES_PASSWORD: ${PASSWORD_DB}
    ports:
      - "5432:5432"