services:
  db:
    container_name: Controle_de_Fluxo_DB
    restat: always
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${}
      POSTGRES_USER: ${}
      POSTGRES_PASSWORD: ${}
    ports:
      - "5432:5432"